octeontx2-af: tim: add missing TIM_AF_RINGX_EXP_OFF register define
The extended-interval config path uses TIM_AF_RINGX_EXP_OFF, but the
register define was never added when that change was backported, breaking
the build:

  error: implicit declaration of function 'TIM_AF_RINGX_EXP_OFF'

Add the missing register define.

Fixes: 2dcc9e93aa5c ("octeontx2-af: tim: clear ring EXP_OFF for extended interval config")

Signed-off-by: Pavan Nikhilesh <pbhagavatula@marvell.com>