coresight: Preserve trace across panic and watchdog reset
This is a combination of 14 commits:

1. coresight: tmc-etr: Fix PREVBOOT mode trace buffer handling

    Fixes the CS_MODE_READ_PREVBOOT mode trace buffer
    management.

2. coresight: tmc-etr: Add support to use reserved memory

    Add support to use reserved memory for coresight ETR trace buffer.
    Hence introduced a ETR buffer mode called ETR_MODE_RESRV, which
    gets selected when ETR device node is supplied with a valid
    memory region.

3. coresight: tmc: Add support for register metadata

    Parse the previous boot register metadata details from
    the device node. This register metadata is used to read
    previous boot preserved trace.

    On platforms that has provision for firmware intervention
    in the watchdog reset path, firmwware is expected to sync
    the metadata region with the coresight register snapshot
    in the specified format.

4. coresight: tmc: Read previous boot trace data

    Read the trace data from the reserved region captured
    during previous boot using register metadata.

    Previous boot trace data has to read before enabling
    to capture fresh trace.

5. coresight: tmc: Keep reserved region parsing common

    TMC ETF needs reserved region for syncing trace data
    from internal SRAM. Hence keep the parsing of reserved
    region common for TMC.

6. coresight: core: Add provision for panic callbacks

    Panic callback handlers allows coresight device drivers to sync
    relevant trace data and trace metadata to reserved memory
    regions so that they can be retrieved later in the subsequent
    boot or in the crashdump kernel.

7. coresight: tmc: Enable panic sync handling

    - Add TMC ETR panic sync handler that syncs register snapshot
      to metadata region
    - Add TMC ETF panic sync handler that syncs register snapshot
      to metadata region and internal SRAM to reserved trace buffer
      region.

8. coresight: etm4x: Configure ETM to trigger on panic

    Configure ETM to generate a trigger on Ext out [0] on panic.
    This is achieved by configuring a single address comparator
    with the address of "panic" and by configuring Ext out [0] to
    trigger on the comparator event.

    This trigger can be used by the sinks to stop capture on panic.

9. coresight: cti: Add CTI id for Neoverse N2 core CTI

    CTI id for Neoverse N2 core CTI.

10. coresight: tmc: Stop trace capture on FlIn

    Configure TMC ETR and ETF to flush and stop trace capture
    on FlIn event. As a side effect, do manual flush only if
    auto flush fails.

11. coresight: tmc-etr: Completely isolate reserve mode ops

    With the change introduced by commit <0abd076217a3>
    (“coresight: tmc-etr: Speed up for bounce buffer in
    flat mode”) that uses dma_sync_single_for_cpu() in
    flat mode ops tmc_etr_sync_flat_buf(), which is not
    compatible to reserve mode buffer allocation API
    dma_map_resource(), hence this patch adds separate
    ops to completely isolate reserve mode from the
    flat mode.

12. coresight: tmc-etr: Support larger trace buffers if reserved memory is insufficient

    In the current reserved memory buffer allocation scheme, we cannot
    allocate trace buffers larger than the reserved memory size. There are
    use cases such as profiling via perf where we need to use large buffers.

    So, add a check in tmc_etr_alloc_resrv_buf() for the requested buffer
    size and fallback to other modes of allocation if the reserved memory
    region is insufficient.

    NOTE: When we fallback to other modes of allocation, preserved memory
    tracing feature cannot be used.

13. coresight: Add panic notifier cleanup

    Add panic notifier cleanup and error handling on
    module exit. This fixes a crash in panic chain
    when module is unloaded.

14. coresight: tmc: etr: Handle enumeration value for CS_MODE_READ_PREVBOOT

    A new `CS_MODE_READ_PREVBOOT` mode was introduced by Commit 7476fa6c3dcd
    ("coresight: tmc: etr: Add support for Marvell OcteonTX2"). However, this
    mode was not accounted for in the `switch` statement of `etm4_disable()`.

    This leads to a build failure when `CONFIG_WERROR` is enabled, with the
    following error message:

    drivers/hwtracing/coresight/coresight-etm4x-core.c:1050:9: error:
    enumeration value 'CS_MODE_READ_PREVBOOT' not handled in switch
    [-Werror=switch]
     1050 |         switch (mode) {
          |         ^~~~~~

Change-Id: Iaa68cb475604b629415e09ea4b46aea0510eac64
Signed-off-by: Amit Singh Tomar <amitsinght@marvell.com>
Signed-off-by: Petr Malat <petr.malat.ext@nokia.com>
Signed-off-by: Linu Cherian <lcherian@marvell.com>
Signed-off-by: Anil Kumar Reddy <areddy3@marvell.com>

Signed-off-by: Tanmay Jagdale <tanmay@marvell.com>