fix: cesa: use proper config name for MV_CESA
	In newer version of LK (>3.10) the MV_CESA is enabled with use of
	CONFIG_MV_INCLUDE_CESA. The CONFIG_MV_CESA_OCF and
	CONFIG_MV_CESA_OCF_KW2 are deprecated and were used only in older
	LSP, where the dts was not supported.

	This commit fixes issue with compilation dependency introduced in
	commit: ocf: fix compilation error when not working with cesa

Change-Id: Ie03454b8f1b3601805f692af2dc27334c1813a77
Signed-off-by: Grzegorz Jaszczyk <jaz@semihalf.com>
Signed-off-by: Nadav Haklai <nadavh@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/19456
Tested-by: Star_Automation <star@marvell.com>