crypto: octeontx2: Export missing symbol
Export missing symbol 'otx2_cpt_sync_mbox_bbuf' to fix
compilation error when building driver as module:
 ERROR: modpost: "otx2_cpt_sync_mbox_bbuf"
	[drivers/crypto/marvell/octeontx2/rvu_cptpf.ko] undefined!
 ERROR: modpost: "otx2_cpt_sync_mbox_bbuf"
	[drivers/crypto/marvell/octeontx2/rvu_cptvf.ko] undefined!

Change-Id: I977e0fe66a15332fd2d216f5cc0540ff9370807f
Signed-off-by: Bharat Bhushan <bbhushan2@marvell.com>
Reported-by: Stefan Wiehler <stefan.wiehler@nokia.com>
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/136831
Tested-by: sa_ip-sw-jenkins <sa_ip-sw-jenkins@marvell.com>
Reviewed-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>