net: mvpp2x: change driver name to avoid registration error
In case both mvpp2 and mvpp2x are compiled into the kernel during boot
one will get following error from driver_register():

Error: Driver 'mvpp2' is already registered, aborting..

That happens because both drivers have name set to 'mvpp2'.
This patch fixes that by changing mvpp2x driver's name to 'mvpp2x'.

Signed-off-by: Tomasz Duszynski <tdu@semihalf.com>