usb: host: xhci: mvebu: add reset on resume quirk
	The resume operation of mvebu xHCI host have some issues,
	so The XHCI_RESET_ON_RESUME quirk is added for it.

Signed-off-by: Ofer Heifetz <oferh@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/18774
Reviewed-by: Nadav Haklai <nadavh@marvell.com>
Tested-by: Nadav Haklai <nadavh@marvell.com>

Conflicts:
	drivers/usb/host/xhci-mvebu.c

fix compilation error
Signed-off-by: Grzegorz Jaszczyk <jaz@semihalf.com>

Change-Id: I4261625f738086f698f028416b66074028d45bf4
Reviewed-on: http://vgitil04.il.marvell.com:8080/27490
Reviewed-by: Lior Amsalem <alior@marvell.com>
Tested-by: Lior Amsalem <alior@marvell.com>