mvebu: prestera: disable redefinition of dummy INTER_REGS_VIRT_BASE
	A dummy entry for INTER_REGS_VIRT_BASE was introduced in the patch:
	"mvebu: prestera: dummy hard-code to remove compilation error"

	* this entry overrides msys defintion (in msys.h)
	- set this dummy entry only if not defined already

Change-Id: I6c6938033d433ef851c8b367fd81a46d33401c84
Signed-off-by: Omri Itach <omrii@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/18105
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Nadav Haklai <nadavh@marvell.com>