arm64: dts: Fix cn9130-crb-*-C.dtb build
Added the missing device-tree nodes to fix the following issue:

Error: .../cn913x-ep.dtsi:34.1-10 Label or path dma_xor0 not found
Error: .../cn913x-ep.dtsi:38.1-10 Label or path dma_xor1 not found
Error: .../cn913x-ep.dtsi:58.1-16 Label or path cp0_pci_ep_uio not found
Error: .../cn913x-ep.dtsi:62.1-13 Label or path cp0_pcie_ep not found
Error: .../cn913x-ep.dtsi:66.1-15 Label or path cp0_armada_ep not found
Error: .../cn913x-ep.dtsi:70.1-14 Label or path cp0_mdio_uio not found
Error: .../cn913x-ep.dtsi:74.1-15 Label or path cp0_xmdio_uio not found

Signed-off-by: Wilson Ding <dingwei@marvell.com>
Change-Id: I5a875dcd3c64929a459c19c5589accc5859c51e6
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/149737
Tested-by: sa_ip-sw-jenkins <sa_ip-sw-jenkins@marvell.com>
Reviewed-by: Sanghoon Lee <salee@marvell.com>